[versions]
shadow = "9.0.0-beta16"
gson = "2.13.1"
licenser = "0.7.5"

# compile only
jetbrains-annotations = "26.0.2"
kotlin = "2.0.21"

[libraries]
shadow = { group = "com.gradleup.shadow", name = "com.gradleup.shadow.gradle.plugin", version.ref = "shadow" }
licenser = { group = "net.neoforged.licenser", name = "net.neoforged.licenser.gradle.plugin", version.ref = "licenser" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }
kotlin-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-sam = { group = "org.jetbrains.kotlin", name = "kotlin-sam-with-receiver", version.ref = "kotlin" }

[plugins]
licenser = { id = "net.neoforged.licenser", version.ref = "licenser" }