[versions]
shadow = "8.3.5"
gson = "2.11.0"
licenser = "0.6.1"

# compile only
jetbrains-annotations = "26.0.1"
kotlin = "2.1.0"

[libraries]
shadow = { group = "com.gradleup.shadow", name = "com.gradleup.shadow.gradle.plugin", version.ref = "shadow" }
licenser = { group = "gradle.plugin.org.cadixdev.gradle", name = "licenser", version.ref = "licenser" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }
kotlin-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-sam = { group = "org.jetbrains.kotlin", name = "kotlin-sam-with-receiver", version.ref = "kotlin" }

[plugins]
licenser = { id = "org.cadixdev.licenser", version.ref = "licenser" }